name: Deploy to Debian VPS

on:
  push:
    branches: [ master ]  # Changed from main to master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '23.11.0'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: npm test || echo "No tests found, skipping..."

  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          # Navigate to project directory
          cd /home/deploy/tryoutgo
          
          # Pull latest changes
          git pull origin master
          
          # Install/update dependencies
          npm install --production
          
          # Restart your application
          pm2 restart tryoutgo || pm2 start app.js --name tryoutgo
          
          echo "✅ Deployment completed successfully!"
